# Generated by Django 4.2.4 on 2023-08-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbook', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ph_no',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='username',
        ),
    ]
